/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMarketQuotesRouteImport } from './routes/api/public/market/quotes'
import { Route as ApiPublicMarketFinnhubTokenRouteImport } from './routes/api/public/market/finnhub-token'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketQuotesRoute = ApiPublicMarketQuotesRouteImport.update({
  id: '/api/public/market/quotes',
  path: '/api/public/market/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketFinnhubTokenRoute =
  ApiPublicMarketFinnhubTokenRouteImport.update({
    id: '/api/public/market/finnhub-token',
    path: '/api/public/market/finnhub-token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/market/finnhub-token': typeof ApiPublicMarketFinnhubTokenRoute
  '/api/public/market/quotes': typeof ApiPublicMarketQuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/market/finnhub-token': typeof ApiPublicMarketFinnhubTokenRoute
  '/api/public/market/quotes': typeof ApiPublicMarketQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/market/finnhub-token': typeof ApiPublicMarketFinnhubTokenRoute
  '/api/public/market/quotes': typeof ApiPublicMarketQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/market/finnhub-token'
    | '/api/public/market/quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/market/finnhub-token'
    | '/api/public/market/quotes'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/market/finnhub-token'
    | '/api/public/market/quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicMarketFinnhubTokenRoute: typeof ApiPublicMarketFinnhubTokenRoute
  ApiPublicMarketQuotesRoute: typeof ApiPublicMarketQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/quotes': {
      id: '/api/public/market/quotes'
      path: '/api/public/market/quotes'
      fullPath: '/api/public/market/quotes'
      preLoaderRoute: typeof ApiPublicMarketQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/finnhub-token': {
      id: '/api/public/market/finnhub-token'
      path: '/api/public/market/finnhub-token'
      fullPath: '/api/public/market/finnhub-token'
      preLoaderRoute: typeof ApiPublicMarketFinnhubTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicMarketFinnhubTokenRoute: ApiPublicMarketFinnhubTokenRoute,
  ApiPublicMarketQuotesRoute: ApiPublicMarketQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
